# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5834c67c9dba95f486921f9f9e7339e4d870ce3c33534969211f8d0320f4885ff4fcd5b45c70db71d163a01eff886d7c39058baf727f34ae99870dc6268fdcf6

test:
  secret_key_base: 988dd6dad6d6b6beed85ec86434f92b2d3a5cafa751205d100d47773735716b8e01fadbacd2b6ab4ed594470bba905ce8ea527bf26e4ae7ba27898d32a89cb13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
